name: first workflow
on : [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Print message
          run : echo " Hello Praveen Potti"
        - name: Step 1 - Checkout code
          uses: actions/checkout@v3
        - name: Step 2 - Run Script
          run: echo "Running Build"
        - name: Step 3 - Python Script
          run: python3 --version